server:
  port: 8503
#jasypt加密的密匙（写到启动参数里面:环境变量password=xxx）
jasypt:
  encryptor:
    password: xccit_zxyp
    algorithm: PBEWithMD5AndDES
spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_zxyp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: ENC(TlTQPte0VeShtLzIGcwfag==)
    password: ENC(9pqTKehechCtcIM24UfmeA==)
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml