server:
  port: 8502
spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  data:
    redis:
      host: localhost
      port: 6379