server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_zxyp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1209
  data:
    redis:
      host: 127.0.0.1
      port: 6379
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml

# web配置
zxyp:
  web:
    auth:
      noAuthUrls:
        - /admin/system/index/login
        - /admin/system/index/generateValidateCode
        - /admin/system/swagger
        - /doc.html
        - /swagger-ui.html
        - /admin/system/minio

# 文件上传MINIO配置
minio:
  endpoint: http://localhost:9000/
  bucket: zxyp-bucket
  accessKey: Sj7W2M3N5Js6MzrsR5GC
  secretKey: XGhGhMob8DnoeH8ZupBLC7B2MzGvWCgN8krkpZRS