server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_zxyp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&
    username: root
    password: 1209
  data:
    redis:
      host: 127.0.0.1
      port: 6379
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml
